[env:esp32-s3-devkitc-1]
 platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
  bodmer/TFT_eSPI
  https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.0

board_build.filesystem = littlefs
board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi

build_unflags =
  -std=gnu++11

build_flags =
  -std=gnu++17
  -DBOARD_HAS_PSRAM
  -DUSER_SETUP_LOADED
  -DUSE_FSPI_PORT
  -DST7789_DRIVER
  -DTFT_INVERSION_ON
  -DTFT_RGB_ORDER=0
  -DTFT_WIDTH=240
  -DTFT_HEIGHT=320
  -DTFT_MISO=-1
  -DTFT_MOSI=11
  -DTFT_SCLK=12
  -DTFT_CS=10
  -DTFT_DC=9
  -DTFT_RST=13
  -DTFT_BL=8
  -DLOAD_GLCD
  -DLOAD_GFXFF
  -DSMOOTH_FONT
  -DSPI_FREQUENCY=40000000
  -DSPI_READ_FREQUENCY=20000000
